[build]
  # The directory where the build system installs dependencies
  base = "/"
  
  # The directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # The build command
  command = "pnpm install && pnpm run build"

# Production context settings
[context.production]
  environment = { NODE_VERSION = "20" }

# Deploy Preview context settings
[context.deploy-preview]
  environment = { NODE_VERSION = "20" }

# Branch Deploy context settings
[context.branch-deploy]
  environment = { NODE_VERSION = "20" }

# Dev context settings
[context.dev]
  environment = { NODE_VERSION = "20" }

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;" 